### ISSUE TITLE
Check "Location" does not check properly

### ISSUE THREAD

**Issue by muffl0n** [stepci/runner#108]
# Given #
A call to httpbin.org, which returns a redirect to `/foo`:
```
-> % curl -I "https://httpbin.org/redirect-to?url=/foo&status_code=301"
HTTP/2 301 
date: Tue, 11 Apr 2023 13:35:11 GMT
content-type: text/html; charset=utf-8
content-length: 0
server: gunicorn/19.9.0
location: /foo
access-control-allow-origin: *
access-control-allow-credentials: true
```

# Expected #
First step would pass, second test would fail:
```
version: "1.1"
name: redirect
tests:
  redirect:
    steps:
      - name: success
        http:
          url: https://httpbin.org/redirect-to?url=/foo&status_code=301
          method: GET
          followRedirects: false
          check:
            status: 301
            Location: /foo
      - name: fail
        http:
          url: https://httpbin.org/redirect-to?url=/foo&status_code=301
          method: GET
          followRedirects: false
          check:
            status: 301
            Location: /foo/
```

# Reality #
Both steps pass:
```
 PASS  redirect

Tests: 0 failed, 1 passed, 1 total
Steps: 0 failed, 0 skipped, 2 passed, 2 total
Time:  1.715s, estimated 2s
CO2:   0.00000g

Workflow passed after 1.715s
```

`/foo` and `/foo/` is clearly not the same URL.
