### ISSUE TITLE
(Breaking) Engine support

### ISSUE THREAD

**Issue by mishushakov** [stepci/runner#51]
We want to be able to support different execution engines/runtimes/drivers (we have yet to agree on wording).
I propose changing the workflow syntax to reflect that

Current:

```yaml
version: "1.0"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - name: GET request
        url: https://{{env.host}}
        method: GET
        check:
          status: /^20/
```

Proposed:

```yaml
version: "1.0"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - name: GET request
        http:
          url: https://{{env.host}}
          method: GET
          check:
            status: /^20/
```

**Comment by mishushakov** [comment]
I suggest changing the workflow syntax to reflect that we support multiple engines/runtimes (we have yet to agree on wording)

Current:

```yaml
version: "1.0"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - name: GET request
        url: https://{{env.host}}
        method: GET
        check:
          status: /^20/
```

Proposed:

```yaml
version: "1.0"
name: Status Check
env:
  host: example.com
tests:
  example:
    steps:
      - http:
          name: GET request
            url: https://{{env.host}}
            method: GET
            check:
              status: /^20/
```
