### ISSUE TITLE
When using a regular expression, the string after the `/` in the middle is ignored.

### ISSUE THREAD

**Issue by koki-develop** [stepci/runner#80]
For example, the following workflow checks the `Content-Type` header of the `https://jsonplaceholder.typicode.com/posts/2` response.
The actual response `Content-Type` header is `application/json; charset=utf-8`.

If specify a regular expression containing `/`, such as `/^application/json/`, the characters after the middle `/` are ignored.
For example, `/^application/foobar/` is expected to fail, but will pass.

If use `match` explicitly, it works fine.

```yaml
# workflow.yml
version: "1.1"
name: Validating Header

config:
  http:
    baseURL: https://jsonplaceholder.typicode.com

env:
  postId: "2"

tests:
  example:
    steps:
      - http:
          url: /posts/${{env.postId}}
          method: GET
          check:
            headers:
              # The response content-type header is `application/json; charset=utf-8`.
              # Looks like it works fine, but "json" is ignored
              Content-Type: /^application/json/ # => passed
      - http:
          url: /posts/${{env.postId}}
          method: GET
          check:
            headers:
              # Expect failure, but this will succeed.
              Content-Type: /^application/foobar/ # => passed
      - http:
          url: /posts/${{env.postId}}
          method: GET
          check:
            headers:
              # Explicitly using match works well.
              Content-Type:
                - match: ^application/foobar # => failed
```

Is this intended behavior?

## Versions

- node v16.17.0
- @stepci/runner v1.7.0
